# Use the official Microsoft .NET SDK image to build the project
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
# Copy csproj and restore as distinct layers
COPY ["ZATCA-V2/ZATCA-V2.csproj", "ZATCA-V2/"]
RUN dotnet restore "ZATCA-V2/ZATCA-V2.csproj"
# Copy everything else and build
COPY . .
WORKDIR "/src/ZATCA-V2"
RUN dotnet build "ZATCA-V2.csproj" -c Release -o /app/build
RUN dotnet tool install --global dotnet-ef --version 6.*
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet publish "ZATCA-V2.csproj" -c Release -o /app/publish
WORKDIR /app
ENTRYPOINT ["dotnet", "ZATCA-V2.dll"]